# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp-dec-kit.dtb \
	stm32mp-dec-kit-headless.dtb \
	stm32mp-dec-kit-5.5.dtb \
	stm32mp-dec-kit-7.0.dtb \
	stm32mp-dec-kit-10.1.dtb \
	stm32mp215f-dk.dtb \
	stm32mp235f-dk.dtb \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb
